#define WIDTH 1500
#define HEIGHT 500
#define MARGIN_TOP 0
#define MARGIN_BOTTOM 100
#define MARGIN_RIGHT 0
#define MARGIN_LEFT 0

#define FONT "Sans"
#define FONT_SIZE 52.0
#define FONT_WEIGHT CAIRO_FONT_WEIGHT_NORMAL
#define FONT_SLANT CAIRO_FONT_SLANT_NORMAL
